name: mlcapstone
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - numpy=1.24.3
  - pandas=2.0.3
  - scikit-learn=1.3.0
  - xgboost=1.7.6
  - psycopg2-binary=2.9.7
  - sqlalchemy=1.4.49
  - mlflow=2.6.0
  - evidently=0.4.1
  - flask=2.2.5
  - pytest=7.4.0
  - python-dotenv=1.0.0
  - python-json-logger=2.0.7
  - feature-engine=1.6.1
  - optuna=3.2.0
  - sweetviz=2.3.1
  - seaborn
  - shap=0.40.0
  - pip:
    - -r requirements.txt       # any extra pip‑only packages
